### PR TITLE
Remove extra script used simply for tee

### PR DESCRIPTION
**Pull request by jmrodri**
By putting entire script in a function you can redirect stdout/err to tee.

main() {
 # do stuff
}

main "$@" 2>&1 | tee output.txt

source: http://wiki.bash-hackers.org/commands/builtin/exec

Alternatively if we don't want it to print out to the console at all, we
can do the following:

logfile=$0.log
exec > $logfile 2>&1
echo "Hello From $0"

I wanted to keep funcationality the same so I chose the tee option.

### CODE REVIEW

**Comment by jwmatthews** [comment]
That's cool!

**Comment by jmontleon** [comment]
ACK.

**Comment by jmontleon** [comment]
https://github.com/fusor/fusor-undercloud-installer/blob/master/fusor-undercloud-installer.spec#L29 and https://github.com/fusor/fusor-undercloud-installer/blob/master/fusor-undercloud-installer.spec#L36 need to be removed as well and then ACK.

**Comment by jmrodri** [comment]
@jmontleon DONE

**Pull request merged**
